site_name: Fiware-Cepheus
repo_url: https://github.com/Orange-OpenSource/fiware-cepheus
site_description: FIWARE Cepheus Documentation
docs_dir: 'doc'
markdown_extensions: [toc,fenced_code]
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'Cepheus-CEP':
  - 'Overview': 'cep/index.md'
  - 'Configuration': 'cep/configuration.md'
  - 'NGSI mapping': 'cep/mapping.md'
- 'Cepheus-Broker': 'broker/index.md'
- 'Examples':
  - '1 Rooms and Floors': examples/1_RoomsAndFloors/index.md
  - '2 Close Shutters': examples/2_CloseShutters/index.md
  - '3 CEP and Broker': examples/3_CepAndBroker/index.md
